# Generated by Django 3.0.8 on 2020-09-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulls_cows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_nickname',
            field=models.TextField(default='AwesomeUser', max_length=50),
        ),
    ]
